export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'About Me',
  headline: 'Engineering Student at QUT',
  description:'So... a bit about me. I am a fulltime student studying 3rd Year Electrical Engineering with a minor in IT and Software Engineering at QUT. ',
  description2:'I enjoy Engineering because it involves taking complex problems and finding a suitable solution to make our everyday lives easier. ',
  description3:'When I am not studying, you will find me in the gym or behind the DJ decks.',
  buttonLabel: 'Click here to see my LinkedIn!',
  buttonURL:"https://www.linkedin.com/in/adammwilliamss/",
  imgStart: false,
  img: require('../../images/img-1.jpeg'),
  alt: 'about-icon',
  dark: true,
  primary: true,
  darkText: false,
};


export const homeObjTwo = {
  id: 'exp',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Experience',
  headline: 'Coder and Manager',
  description:'Throughtout my studies I have gained kowledge on many coding languages such as C,Python, MATLAB, React and Javascript.',
  description3:'In addition the past 2 years I have been an assistant manager for a Dominos store that is earning $45,000 a week. In turn teaching skills in management, resposibility, team cooperation and problem solving.',
  buttonLabel: 'Learn More',
  buttonURL:"https://www.linkedin.com/in/adammwilliamss/",
  imgStart: true,
  img: require('../../images/exp.png'),
  alt: 'expimg',
  dark: false,
  primary: false,
  darkText: true,
};